version: '3.8'
services:
  api:
    container_name: graphql-api
    build: api
    image: graphql-api
    volumes:
      - ./api/app:/opt/pysetup/app:delegated
    ports:
      - '4000:8000'
    networks:
      graphql-network:
        aliases:
          - graphql-api
networks:
  graphql-network:
